version: '2'

services:
  phpapp:
    image: 'php:7.2-apache'
    ports:
      - '8080:80'
    volumes:
      - './phpapp:/var/www/html'
  webapp:
    image: 'bitnami/apache:latest'
    ports:
      - '6080:8080'
      - '4443:8443'
    volumes:
      - './webapp:/app'
    depends_on:
      - phpapp
