version: '3'

services:
  php:
    image: 'php:7.2-apache'
    container_name: phpapp
    networks:
      mynet:
        aliases:
          - phpnet
    ports:
      - '8080:80'
    volumes:
      - './phpapp:/var/www/html'
  web:
    image: 'bitnami/apache:latest'
    container_name: webapp
    networks:
      - mynet
    ports:
      - '6080:8080'
      - '4443:8443'
    volumes:
      - './webapp:/app'
    depends_on:
      - php
    
  networks:
    mynet:
