version: '3'

services:
  php:
    image: 'php:7.2-apache'
    container_name: phpapp
    hostname: phpapp
    networks:
      phpnet:
    ports:
      - '8080:80'
    volumes:
      - './phpapp:/var/www/html'
  node:
    build: ./nodeapp
    container_name: nodeapp
    hostname: nodeapp
    networks:
      - phpnet
      - nodenet
    ports:
      - '3000:3000'
    volumes:
      - './nodeapp:./'
    depends_on:
      - php
    
networks:
  phpnet:
  nodenet:
